### ISSUE TITLE
Counter seems broken when you visit a community link directly

### ISSUE THREAD

**Issue by kerodkibatu** [dagmawibabi/TelegramCommunityGallery#22]
I've noticed that the counter(the one at the top of the page) appears to be malfunctioning when I visit a community link directly (i.e. without navigating from another page).

For example, if I go straight to [Example Channel](https://telegram.dagmawi.dev/@dotnetwarrior), the counter doesn't update correctly. This behavior is different from what happens when I navigate to the same community link through other means (e.g. clicking on it from the homepage/searching for it).

![image](https://github.com/dagmawibabi/TelegramCommunityGallery/assets/88666160/ab3ba94b-c27d-4a26-8989-f14a7ceebd14)

**Comment by dagmawibabi** [comment]
And fixed it 😉
